name: Package and release

on:
  push:
    tags:
      - '**'

jobs:

  release:

    runs-on: ubuntu-latest

    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Clone project
        uses: actions/checkout@v1

      - name: Package and release
        uses: BigWigsMods/packager@v1

      # another example where we supply additional arguments, this example is specifically to release
      # for the Burning Crusade Classic version of the game and doesn't upload to WoWInterface
      - name: Package and release for Burning Crusade Classic
        uses: BigWigsMods/packager@v1
        with:
          args: -g bcc -w 0